name       : innoextract
version    : '1.8'
release    : 7
source     :
    - https://github.com/dscharrer/innoextract/releases/download/1.8/innoextract-1.8.tar.gz : 5e78f6295119eeda08a54dcac75306a1a4a40d0cb812ff3cd405e9862c285269
license    : Zlib
component  : system.utils
summary    : A tool to unpack installers created by Inno Setup
description: |
    A tool to unpack installers created by Inno Setup
builddeps  :
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
