name       : innoextract
version    : '1.9'
release    : 10
source     :
    - https://github.com/dscharrer/innoextract/releases/download/1.9/innoextract-1.9.tar.gz : 6344a69fc1ed847d4ed3e272e0da5998948c6b828cb7af39c6321aba6cf88126
license    : Zlib
component  : system.utils
summary    : A tool to unpack installers created by Inno Setup
description: |
    A tool to unpack installers created by Inno Setup
builddeps  :
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
