name       : innoextract
version    : '1.7'
release    : 5
source     :
    - http://constexpr.org/innoextract/files/innoextract-1.7/innoextract-1.7.tar.gz : c1efb732f2bc3a80065c5f51a0d4ea6027aebf528c609d3f336aea2055d2f0a4
license    : Zlib
component  : system.utils
summary    : A tool to unpack installers created by Inno Setup
description: |
    A tool to unpack installers created by Inno Setup
builddeps  :
    - pkgconfig(liblzma)
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
